### PR TITLE
feat: Adding documentation about Link Error Messages [wt-414]

### PR DESCRIPTION
**Pull request by joaosf**
Adding description about new Link Error Messages

## Description

Adding documentation about new Link Error Messages, pattern:

```
Error code - Error Message

User Options
Next Step
```

## Resolved issues
Jira:

### Before submitting the PR, please consider the follow:
- [ ] It's beneficial if your pull request references an issue used to discuss the pull request ahead of time. If you haven't previously created an issue, please create one and discuss your contribution with the maintainers.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [ ] The description should clearly illustrate what problems the pull request solves.
- [ ] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is up to date with the `main` branch.

### CODE REVIEW

**Review by sprngbk — COMMENTED** [review]
We have a [Link SDK reference](https://docs.x.immutable.com/docs/link-setup) section in our docs. Would it be better to put the error codes within each method page instead of a separate section?

**Comment by sprngbk** [comment]
I was thinking that all of the Link SDK methods [here](https://docs.x.immutable.com/docs/sdk-api) should have error codes. Thanks to this PR, most of them now do, however, can we add them for the following (or at least link to another method if the error codes are the same)?
* https://docs.x.immutable.com/docs/linkpreparewithdrawal
* https://docs.x.immutable.com/docs/linksyncstate
* https://docs.x.immutable.com/docs/linksign

Also, are there general error codes? Do we need a page for those?

**Comment by joaosf** [comment]
> I was thinking that all of the Link SDK methods [here](https://docs.x.immutable.com/docs/sdk-api) should have error codes. Thanks to this PR, most of them now do, however, can we add them for the following (or at least link to another method if the error codes are the same)?
> 
> * https://docs.x.immutable.com/docs/linkpreparewithdrawal
> * https://docs.x.immutable.com/docs/linksyncstate
> * https://docs.x.immutable.com/docs/linksign
> 
> Also, are there general error codes? Do we need a page for those?

I move to a new page "Link Error Codes", request and validate with Lilly/Eduardo

**Comment by sprngbk** [comment]
Hi @joaosf, can I please request the following changes:
* Put the error codes page under the [Link SDK heading](https://docs.x.immutable.com/docs/sdk-api)
* Call this page `Link Errors` instead of `Link Errors Table` (update the page slug as well)
* In each of the function pages that have specific error codes (ie. [deposit](https://docs.x.immutable.com/docs/link-deposit-options)), add a heading called `Errors` and underneath that, have "See error responses here." - "here" is linked to the relevant section in the main error page (see image below 👇)

image

Thank you!

**Comment by joaosf** [comment]
> Hi @joaosf, can I please request the following changes:
> 
> * Put the error codes page under the [Link SDK heading](https://docs.x.immutable.com/docs/sdk-api)
> * Call this page `Link Errors` instead of `Link Errors Table` (update the page slug as well)
> * In each of the function pages that have specific error codes (ie. [deposit](https://docs.x.immutable.com/docs/link-deposit-options)), add a heading called `Errors` and underneath that, have "See error responses here." - "here" is linked to the relevant section in the main error page (see image below 👇)
> 
> image
> 
> Thank you!

Fixed

**Review by sprngbk — APPROVED** [review]

**Pull request merged**
